# -*- coding: utf-8 -*-
"""even or prime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lJW8ekXifkZrDpBCGOZlPwVbJMVQHwkR
"""

import numpy as np

random_numbers = list(np.random.randint(low = 13, high = 789, size = 100))

random_numbers

even = list()

prime = list()

for num in random_numbers:
  if num % 2 == 0:
    even.append(num)

  else:

    for divisor in range(2,num):
      if num % divisor == 0:

        break
    if divisor == (num-1):
      prime.append(num)

even

